### PR TITLE
Fixes html parsing when `//` is present in the children

### LINKED ISSUE #2: double slash is detected as closing tag in some cases
The following seems to break for me, cutting the output at `=https:`. 
```
render: ({params, query, request}) => html`
  <${Html} title="swtl">
    <div>
      <iframe src="https://example.com/page.html"></iframe>
    </div>
<//>`
```
results in 
Screenshot 2023-11-28 at 01 25 55

I tried to monkey patch by adding a check for a preceding angle bracket, it seems to fix my case at least:
in html.js, line 228:
```
// added the first check 
if (statics[i][j] == "<"&& statics[i][j + 1] === "/" && statics[i][j + 2] === "/") {
```

### PR DESCRIPTION
**Pull request by gryzzly**
Before the fix, the detection of a component’s closing tag `<//>` was conflicting with `//` found in component’s content. 

Also adds tests for the case (and tiny bit more).

Fixes #2

### CODE REVIEW

File: tests/tests.js [hunk 1]
```diff
@@ -67,7 +93,7 @@ describe('parsing', () => {
   });
 
   it('handles components with properties and expressions', () => {
-    const result = unwrap(html`<${Foo} a=${1}/>${2}`);
+    const result = unwrap(html`<${Foo} a=${1}/>${2}<//>`);
```
Comment (thepassle) [inline tests/tests.js:96]:
```
<${Foo} a=${1}/>${2}<//>
              ^
```

This one already is self closing, does this test even need any changes?

**Comment by thepassle** [comment]
This looks great, thanks for creating the PR! Left one small comment :)

File: tests/tests.js (hunk 1 above)
Comment (gryzzly) [reply tests/tests.js:96]: ah sorry, my brain tricked me, one sec 👍

**Comment by thepassle** [comment]
Merged in 0.0.23, thanks for the PR!

Would also love to see what you're building with `swtl` if its public to share 🙂

**Comment by gryzzly** [comment]
@thepassle I’m building a client-side CMS that is powered by git, and one of my goals is to only use very plain dependencies where I understand 100% of their source. `swtl` fits perfectly, plus I love the fact it is very web plaform based, plus I’m interested in alternative thinking about what "components" are. I also happened to work on Checkout UI extensions at Shopify which was using web workers for rendering (https://github.com/Shopify/remote-ui), so I’m quite interested in workers (and how come are they used so little). 

Anyway, thanks for building `swtl` in the open, I love this project. 

I’m gonna give you access to the repo once I have something in an mvp state.

**Comment by thepassle** [comment]
That sounds awesome. I'd love to take a look once you have something in mvp state indeed! And let me know if you run into any other issues with SWTL, then we can take a look at how to tackle it 🙂
